language: python
services:
  - mongodb
  - postgresql

before_script:
  - sleep 15
  - psql -c 'create database drongo;' -U postgres
  - psql -c 'create user drongo with password "drongo";' -U postgres
  - psql -c 'grant all privileges on drongo to drongo;' -U postgres

matrix:
  include:
    - python: 2.7
    - python: 3.3
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
    - python: pypy
    - python: pypy3.5

before_install: "pip install codecov"
install: "python setup.py install"
script:
  - pip install -r requirements.txt
  - flake8 drongo_modules
  - py.test --cov
after_success: codecov
