language: python
services:
  - mongodb
before_script:
  - sleep 15

matrix:
  include:
    - python: 2.7
    - python: 3.3
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
    - python: pypy2.7
    - python: pypy3.5

before_install: "pip install codecov"
install: "python setup.py install"
script:
  - pip install -r requirements.txt
  - pip install git+https://github.com/drongo-platform/drongo-core.git
  - flake8 drongo_modules
  - py.test --cov
after_success:
  codecov
